tienda_virtual/ofertas/urls.py
from django.urls import path
from . import views

app_name = 'ofertas'

urlpatterns = [
    path('', views.index, name='index'),
]

tienda_virtual/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    path('', views.index, name='index'),
]

tienda_virtual/tienda_virtual/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('ofertas/', include('ofertas.urls')),
    path('', views.index, name='index')
]

tienda_virtual/ofertas/models.py
from django.db import models

# Create your models here.

tienda_virtual/productos/models.py
from django.db import models

# Create your models here.

class Categorias(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Productos(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    Categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
        
    def __str__(self):
        return self.nombre
    

tienda_virtual/ofertas/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    return render(request,'ofertas/index.html') # Renderizará la plantilla index.html

tienda_virtual/productos/views.py
from django.shortcuts import render
from .models import Productos

# Create your views here.
def index (request):
    productos = Productos.objects.all()
    return render(request,'productos/index.html',{'productos':productos}) 

tienda_virtual/tienda_virtual/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

tienda_virtual/ofertas/templates/ofertas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Ofertas</title>
</head>
<body>
    <div>
        <h1>Bienvenidos a la sección de Ofertas</h1>
    </div>

    <nav>
        <a href="{% url 'productos:index'  %}">Ir a Productos</a>

        <a href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
    </nav>

    <div>
        <h3>Aquí puedes ver la lista de ofertas</h3>

        <ul>
            {% for oferta in ofertas %}
                <li>{{ofertas.nombre}}</li>
            {% empty %}
                <li>No hay ofertas</li>
            {% endfor %}
        </ul>
        
        
    </div>

    <div>
        <h4>Aquí puedes navegar a las otras app o regresar al inicio</h4>
        
        <a href="{% url 'productos:index'  %}">Ir a Productos</a>
        <br>
        <a href="{% url 'index' %}">Ir a la pagina Principal</a>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

tienda_virtual/productos/templates/productos/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Productos</title>
</head>
<body>

    <nav class='nav-link'>
        <a href="{% url 'ofertas:index'  %}">Ir a Ofertas</a>
        <a href="{% url 'index' %}">Ir a la pagina Principal</a>
    </nav>

    <div>
        <h1>Bienvenidos a la sección de Productos</h1>
    </div>

    <div>
        <h2> Listado de Productos</h2>
        <!--
        <style>
            table {
                margin: 0 auto; /* Centrar la tabla */
                border-collapse: separate;
                border-spacing: 15px; /* Espacio entre las celdas */
                width: 80%; /* Ajusta el ancho de la tabla */
            }
            th, td {
                padding: 10px;
                text-align: center;
                border: 1px solid #0004ff; /* Bordes para las celdas */
            }
            th {
                background-color: #ff0000; /* Color de fondo para los encabezados */
            }
        </style>
        -->
        <div class="container">
            <table>
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Precio</th>
                        <th>Categoría</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.precio }}</td>
                        <td>{{ producto.Categoria.nombre }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">
                            <h5>No hay productos disponibles</h5>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
    
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

tienda_virtual/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Tienda Virtual</title>
</head>
<body>
    <header>
        <h1>Pagina Principal</h1>
    </header>

    <nav>
        <a href="{% url 'productos:index'  %}">Ir a Productos</a>

        <a href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
    </nav>

    <div>
        <h2>Bienvenidos a la Tienda Virtual</h2>
    </div>

    <div>
        <h3>Aquí puedes navegar a las otras app o regresar al inicio</h3>
        
        <a href="{% url 'productos:index'  %}">Ir a Productos</a> 
        <br>
        <a href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
    </div>
    
    <br>
    <div class="container">
        <button id="show-alert">SUPER BOTÓN</button>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>